---
galaxy_info:
  author: Werner Dijkerman
  description: Installing and configuring Telegraf
  company:
  license: license BSD
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - monitoring
dependencies: []
