---

### Configure monitoring infrastructure
#- hosts: iperf_servers, iperf_clients
#  remote_user: vagrant
#  become: true
#  gather_facts: yes
#  roles:
#    - snap-telemetry

- hosts: iperf_servers, iperf_clients
  remote_user: vagrant
  become: true
  gather_facts: yes
  roles:
    - telegraf

#- hosts: vizstack-host
#  remote_user: vagrant
#  become: true
#  gather_facts: yes
#  roles:
#    - vizstack

## Play for testing network throughput
#- hosts: ssh_ips
#  remote_user: vagrant
#  become: true
#  gather_facts: yes
#  roles:
#    - netbench