---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
  - name: telegraf-centos
    image: milcom/centos7-systemd
    privileged: True
  - name: telegraf-debian
    image: maint/debian-systemd
    privileged: True

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
