kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: standard
provisioner: kubernetes.io/scaleio
parameters:
  gateway: https://192.168.50.11:8443/api
  protectionDomain: pdomain
  secretNamespace: scaleio
  secretRef: scaleio-secret
  storagePool: pool1
  system: cluster1
