apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-scaleio-controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-scaleio-controller
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-scaleio-controller
subjects:
  - kind: ServiceAccount
    name: csi-scaleio-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: csi-scaleio-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-scaleio-controller
spec:
  serviceName: csi-scaleio-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-scaleio-controller
    spec:
      serviceAccount: csi-scaleio-controller
      containers:
        - name: csi-attacher
          image: docker.io/cduchesne/csi-attacher
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: csi-provisioner
          image: docker.io/cduchesne/csi-provisioner
          args:
            - "--csi-address=$(ADDRESS)"
            - "--provisioner=csi-scaleio"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: csi-scaleio
          image: docker.io/cduchesne/csi-scaleio
          command: [ "/csi-scaleio" ]
          env:
            - name: CSI_ENDPOINT
              value: /var/run/csi/csi.sock
            - name: X_CSI_DEBUG
              value: "true"
            - name: GOSCALEIO_DEBUG
              value: "true"
            - name: X_CSI_SCALEIO_AUTOPROBE
              value: "true"
            - name: X_CSI_SCALEIO_ENDPOINT
              value: https://192.168.50.11:8443
            - name: X_CSI_SCALEIO_USER
              value: admin
            - name: X_CSI_SCALEIO_PASSWORD
              value: Scaleio123
            - name: X_CSI_SCALEIO_INSECURE
              value: "true"
            - name: X_CSI_SCALEIO_SYSTEMNAME
              value: cluster1
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
      volumes:
        - name: socket-dir
          emptyDir:
