# This YAML defines all API objects to create RBAC roles for CSI node plugin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-scaleio-node
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-scaleio-node
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-scaleio-node
subjects:
  - kind: ServiceAccount
    name: csi-scaleio-node
    namespace: default
roleRef:
  kind: ClusterRole
  name: csi-scaleio-node
  apiGroup: rbac.authorization.k8s.io
---
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-scaleio-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: csi-scaleio-node
  template:
    metadata:
      labels:
        app: csi-scaleio-node
    spec:
      serviceAccount: csi-scaleio-node
      hostNetwork: true
      containers:
        - name: csi-scaleio-node
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: docker.io/cduchesne/csi-scaleio
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/kubelet/plugins/com.thecodeteam.scaleio/csi.sock
            - name: X_CSI_DEBUG
              value: "true"
            - name: X_CSI_SCALEIO_AUTOPROBE
              value: "true"
            - name: X_CSI_PRIVATE_MOUNT_DIR
              value: "/var/lib/kubelet/plugins/com.thecodeteam.scaleio/disks"
          volumeMounts:
            - name: driver-path
              mountPath: /var/lib/kubelet/plugins/com.thecodeteam.scaleio
              #mountPropagation: "Bidirectional"
            - name: pods-path
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: dev
              mountPath: /dev
            - name: scaleio-path-opt
              mountPath: /opt/emc
            - name: scaleio-path-bin
              mountPath: /bin/emc
        - name: driver-registrar
          image: docker.io/k8scsi/driver-registrar
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: driver-path
              mountPath: /var/run/csi
      volumes:
        - name: driver-path
          hostPath:
            path: /var/lib/kubelet/plugins/com.thecodeteam.scaleio
            type: DirectoryOrCreate
        - name: pods-path
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: scaleio-path-opt
          hostPath:
            path: /opt/emc
            type: Directory
        - name: scaleio-path-bin
          hostPath:
            path: /bin/emc
            type: Directory
