mongodb:
  persistence:
    enabled: true
    storageClass: scaleio
    accessMode: ReadWriteOnce
    size: 8Gi
persistence:
  enabled: true
  storageClass: scaleio
  accessMode: ReadWriteOnce
  size: 8Gi
