---

- name: Copy iperf script
  template:
    src: iperf.sh.j2
    dest: /tmp/iperf.sh
  mode: a+x

- name: Mod file permissions
  command: chmod a+x iperf.sh
  args:
    chdir: /tmp

- name: Run iperf test
  shell: ./iperf.sh {{ test_count }} {{ item }}
  args:
    chdir: /tmp
  with_items:
    - "{{ groups['iperf_servers'] }}"

- name: Wait for tests
  wait_for:
    timeout: "{{ length_of_benchmark }}"