---

- name: Install pip | {{ ansible_distribution }}
  apt:
    name: python-pip
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install pip | {{ ansible_distribution }}
  yum:
    name: python-pip
    state: present
  when: ansible_distribution == "CentOS"

- name: Install docker-py | {{ ansible_distribution }}
  pip:
    name: docker-py

- name: Instantiate Grafana container | {{ ansible_distribution }}
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    exposed_ports:
      - 3000
    ports:
      - "3000:3000"

- name: Grab Snap plugin | {{ ansible_distribution }}
  command: docker exec grafana bash -l -c "grafana-cli plugins install raintank-snap-app"

- name: Restart container after snap plugin install
  command: docker restart grafana


- name: Create grafana datasource | {{ ansible_distribution }}
  uri:
    url: "http://{{ vizstack_host }}:3000/api/datasources"
    user: "{{ admin_user }}"
    password: "{{ admin_password }}"
    force_basic_auth: yes
    method: POST
    body_format: json
    body: "{{ item | to_json }}"
  with_items: "{{ grafana_datasources }}"
#  #no_log: True
#  #when: datasources.content == "[]"

#- name: Create Grafana Dashboard | {{ ansible_distribution }}
#  uri:
#    url: "http://{{ vizstack_host }}:3000/api/dashboards/import"
#    user: "{{ admin_user }}"
#    password: "{{ admin_password }}"
#    force_basic_auth: yes
#    method: POST
#    body_format: json
#    body: "{{ lookup('file','files/test2.json') }}"