---

- name: Instantiate influxdb container | {{ ansible_distribution }}
  docker_container:
    name: influxdb
    image: influxdb
    volumes:
      - /data
    exposed_ports:
      - 8086
    ports:
      - "8086:8086"

- name: Wait for influxdb to start | {{ ansible_distribution }}
  pause: seconds=15

- name: Create telegraf DB | {{ ansible_distribution }}
  command: docker exec influxdb bash -l -c "influx -execute 'CREATE DATABASE telegraf'"

# TODO : Decide if we want to keep the SNAP infrastructure
#- name: Create snap database | {{ ansible_distribution }}
#  command: docker exec influxdb bash -l -c "influx -execute 'CREATE DATABASE snap_db'"
#
#- name: Create cpu_telemetry database | {{ ansible_distribution }}
#  command: docker exec influxdb bash -l -c "influx -execute 'CREATE DATABASE {{ cpu_telemetry_db }}'"
#
#- name: Create interface_telemetry database | {{ ansible_distribution }}
#  command: docker exec influxdb bash -l -c "influx -execute 'CREATE DATABASE {{ interface_telemetry_db }}'"
#
#- name: Create iostat_telemetry database | {{ ansible_distribution }}
#  command: docker exec influxdb bash -l -c "influx -execute 'CREATE DATABASE {{ iostat_telemetry_db }}'"